import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Script from 'next/script'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div id="qb-posts"></div> 
      <Script src="https://app.quickblog.co/js/embed.js?qb_id=2364EVkqf1XsONsQDHObHSwaCiQbDmAaeyp2cMNGLGs7"></Script>
    </div>
  )
}
